# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: master
  1: chrome
  2: strawberry
  3: deej.unmapped
  4: mic

# use keyboard. follwed by a keyboard key
# look at button.go for the list of keys
# you can open a file by giving the file location
# use / when giving a file location in both windows and linux
# buttons just run a cmd line so you can basically do anything with it.
# just like in sliders you can list commands for a button to execute

button_mapping:
  0: keyboard.lxmute
  1: keyboard.lxprevioussong
  2: keyboard.lxplaypause
  3: keyboard.lxnextsong
  4: strwberry
  5: google-chrome https://youtube.com/
  6: google-chrome https://gmail.com/
  7: mate-terminal
  8: google-chrome

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: /dev/ttyACM0
baud_rate: 115200

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: low

# set this to "serial" to use deej with an arduino board connected via a serial port
# set this to "udp" to listen for slider movements via a UDP network connection
controller_type: udp

# settings for the UDP connection
udp_port: 16990
