name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        mode: [release, dev]
        go: ["1.14"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install prerequisites (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deej (Windows)
        if: runner.os == 'Windows'
        run: pkg/deej/scripts/windows/build-${{ matrix.mode }}.bat
        shell: cmd
      - name: Archive Windows build
        if: runner.os == 'Windows' && matrix.mode == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: deej-release.exe

      - name: Build deej (Linux)
        if: runner.os == 'Linux'
        run: pkg/deej/scripts/linux/build-${{ matrix.mode }}.sh
      - name: Archive Linux build
        if: runner.os == 'Linux' && matrix.mode == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: deej-release